server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework
  servlet:
      context-path: /api
      encoding:
        enabled: false



  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


# 数据库配置
spring:
  config:
    import: optional:file:.env[.properties]

  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              redirect-uri: https://usc.xlearnedu.com/login/oauth2/code/google
            microsoft:
              client-id: ${MICROSOFT_CLIENT_ID}
              client-secret: ${MICROSOFT_CLIENT_SECRET}
              authorization-grant-type: authorization_code
              scope: openid, profile, email
              redirect-uri: https://usc.xlearnedu.com/login/oauth2/code/microsoft
              client-name: Microsoft
              provider: microsoft
            facebook:
              client-id: ${FACEBOOK_CLIENT_ID}
              client-secret: ${FACEBOOK_CLIENT_SECRET}
              redirect-uri: https://usc.xlearnedu.com/login/oauth2/code/facebook
              
          provider:
            google:
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            microsoft:
              authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
              token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
              user-info-uri: https://graph.microsoft.com/oidc/userinfo
              user-name-attribute: sub
              jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
    
  linkedin:
    client-id: ${LINKEDIN_CLIENT_ID}
    client-secret: ${LINKEDIN_CLIENT_SECRET}
    redirect-uri: https://usc.xlearnedu.com/login/oauth2/code/linkedin
    token-url: https://www.linkedin.com/oauth/v2/accessToken
    auth-url: https://www.linkedin.com/oauth/v2/authorization
    scope: openid profile email
              
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/lms_v2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

    hikari:
      maximum-pool-size: 32
      minimum-idle: 8
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 10000
      leak-detection-threshold: 30000

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  hadoop:
    fs:
      defaultFS: hdfs://labserver101.ddns.net:9666 # HDFS 的地址 (替换为你的 Hadoop 集群地址)
      user: admir  # 访问 HDFS 的用户

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  mail:
    host: mail.privateemail.com  # 你的邮件服务器
    port: 587
    username: ${MAIL_USERNAME}  # 你的邮箱
    password: ${MAIL_PASSWORD}  # 你的邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.coursistant.lms.module
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

mail:
    host: mail.privateemail.com  # 你的邮件服务器
    port: 587
    username: ${MAIL_USERNAME}  # 你的邮箱
    password: ${MAIL_PASSWORD}  # 你的邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

minio:
  url: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

lms:
  content:
    max-file-bytes: 209715200

ip: localhost

api:
  base:
    url: ${API_BASE_URL}


token:
  access-expire-hours: 2
  refresh-expire-days: 14
  private-key-path: private.pem
  public-key-path: public.pem

