server:
  port: 9090
  servlet:
    context-path: /api
    encoding:
      enabled: false


# spring配置
spring:
    
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              redirect-uri: http://localhost:5173/login/oauth2/code/google
            microsoft:
              client-id: ${MICROSOFT_CLIENT_ID}
              client-secret: ${MICROSOFT_CLIENT_SECRET}
              authorization-grant-type: authorization_code
              scope: openid, profile, email
              redirect-uri: "https://dash.coursistant.com/login/oauth2/code/microsoft"
              client-name: Microsoft
              provider: microsoft

            facebook:
              client-id: ${FACEBOOK_CLIENT_ID}
              client-secret: ${FACEBOOK_CLIENT_SECRET}
              redirect-uri:  http://localhost:5173/login/oauth2/code/facebook
              
          provider:
            google:
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            microsoft:
              authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
              token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
              user-info-uri: https://graph.microsoft.com/oidc/userinfo
              user-name-attribute: sub
              jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}  #数据库用户名
    password: ${DB_PASSWORD} #数据库密码
    url: jdbc:mysql://labserver101.ddns.net:3306/lms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  hadoop:
    fs:
      defaultFS: hdfs://labserver101.ddns.net:9666 # HDFS 的地址 (替换为你的 Hadoop 集群地址)
      user: admir  # 访问 HDFS 的用户

  mvc:      
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: mail.privateemail.com  # 你的邮件服务器
    port: 587
    username: ${MAIL_USERNAME}  # 你的邮箱
    password: ${MAIL_PASSWORD}  # 你的邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  linkedin:
    client-id: ${LINKEDIN_CLIENT_ID}
    client-secret: ${LINKEDIN_CLIENT_SECRET}
    redirect-uri: https://dash.coursistant.com/re
    token-url: https://www.linkedin.com/oauth/v2/accessToken
    auth-url: https://www.linkedin.com/oauth/v2/authorization
    scope: openid profile email


  redis:
    general:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 2
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    adminAll:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 3
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    adminPage:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 4
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    userAll:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 5
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    userPage:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 6
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    courseAll:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 7
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    coursePage:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 8
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    teachAll:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 9
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    teachPage:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 10
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    learnAll:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 11
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    learnPage:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 12
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2

    refreshToken:
      host: labserver101.ddns.net
      port: 6381
      username: ${REDIS_DEFAULT_USERNAME}
      password: ${REDIS_DEFAULT_PASSWORD}
      database: 13
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2


# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coursistant.lms.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost