package com.coursistant.lms.module.interaction.notification.enums;

public enum FailureCategory {
    RETRYABLE_TIMEOUT,
    RETRYABLE_NETWORK,
    RETRYABLE_PROVIDER_5XX,
    RETRYABLE_RATE_LIMIT,
    RETRYABLE_CHANNEL_PERSIST,
    PERMANENT_NO_EMAIL,
    PERMANENT_INVALID_EMAIL,
    PERMANENT_MISSING_TEMPLATE,
    PERMANENT_RECIPIENT_INVALID,
    PERMANENT_PREFERENCE,
    ORPHAN_MAX_ATTEMPTS,
    UNKNOWN_OUTCOME
}
