package com.coursistant.lms.module.interaction.notification.enums;

public enum NotificationType {
    ANNOUNCEMENT_POSTED,
    ASSIGNMENT_PUBLISHED,
    ASSIGNMENT_SUBMISSION_RECEIVED,
    ASSIGNMENT_GRADE_RELEASED,
    QUIZ_GRADE_RELEASED,
    ASSIGNMENT_GRADE_CORRECTED,
    QUIZ_GRADE_CORRECTED,
    WEEK_PUBLISHED,
    ASSIGNMENT_SCHEDULE_CHANGED,
    QUIZ_PUBLISHED,
    QUIZ_SCHEDULE_CHANGED,
    QUIZ_TIME_LIMIT_CHANGED,
    COURSE_EVENT_CREATED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    GROUP_MEMBER_MOVED
}
